
version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model_api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "dvc pull && uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"

    volumes:
      - ./:/app
      - wandb_data:/app/models/wandb


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus


volumes:
  wandb_data:
