global:
  scrape_interval: 15s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus lui-même

  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # FastAPI (via Instrumentator)
